// GENERATED by scripts/build-agent-api.mjs from server/*.ts — do not edit.

// server/bills.ts
import { isAddress } from "viem";

// server/chain.ts
import { createPublicClient, createWalletClient, defineChain, fallback, http } from "viem";
import { privateKeyToAccount } from "viem/accounts";
var IS_MAINNET = (process.env.VITE_ARC_NETWORK ?? "").trim() === "mainnet";
var USDC = { symbol: "USDC", address: "0x3600000000000000000000000000000000000000", decimals: 6 };
var NETWORKS = {
  testnet: {
    chainId: 5042002,
    name: "Arc Testnet",
    explorer: "https://explorer.testnet.arc.io",
    rpcs: ["https://rpc.testnet.arc.io", "https://rpc.testnet.arc.network"],
    // Same registry as src/tokens.ts
    tokens: [USDC, { symbol: "EURC", address: "0x89B50855Aa3bE2F677cD6303Cec089B5F319D72a", decimals: 6 }],
    // Synthra — verified: router factory() matches, USDC/EURC pools funded
    swap: {
      venue: "Synthra",
      router: "0xA545bCB1Bd7985c59ea162aB1748A0803434C31b",
      quoter: "0x3Ce954107b1A675826B33bF23060Dd655e3758fE",
      feeTiers: [100, 500, 3e3, 1e4],
      slippageBps: 50n
    },
    arcNames: "0x578dbd5734f13bca66a1355cca296c07823892a2",
    betaMaxPerDay: null
  },
  mainnet: {
    chainId: 5042,
    name: "Arc",
    explorer: "https://explorer.arc.io",
    rpcs: [
      "https://rpc.mainnet.arc.io",
      "https://rpc.blockdaemon.mainnet.arc.io",
      "https://rpc.drpc.mainnet.arc.io",
      "https://rpc.quicknode.mainnet.arc.io"
    ],
    tokens: [USDC],
    // No verified USDC/EURC pools on mainnet yet — the swap tool is off
    swap: null,
    arcNames: "0xF2DCe7fe2864FDD899b12185c610C11d425200d9",
    // Unaudited vault holding real money: refuse vaults whose daily limit is above this
    // (whole tokens; same cap as BETA_MAX_PER_DAY in src/agent-config.ts)
    betaMaxPerDay: 50
  }
};
var NET = IS_MAINNET ? NETWORKS.mainnet : NETWORKS.testnet;
var CHAIN_ID = NET.chainId;
var NETWORK_NAME = NET.name;
var EXPLORER = NET.explorer;
var TOKENS = NET.tokens;
var SWAP = NET.swap;
var ARC_NAMES = NET.arcNames;
var BETA_MAX_PER_DAY = NET.betaMaxPerDay;
var arcChain = defineChain({
  id: CHAIN_ID,
  name: NETWORK_NAME,
  nativeCurrency: { name: "USDC", symbol: "USDC", decimals: 18 },
  rpcUrls: { default: { http: [...NET.rpcs] } }
});
var publicClient = createPublicClient({
  chain: arcChain,
  transport: fallback(arcChain.rpcUrls.default.http.map((u) => http(u, { retryCount: 2, timeout: 15e3 })))
});

// server/bills.ts
var API = "https://api.bitrefill.com/v2";
var PAYMENT_METHOD = "usdc_base";
var DEFAULT_MAX_USDC = 100;
var CATEGORIES = {
  airtime: true,
  data: true,
  electricity: true,
  tv: true,
  exams: true
};
function env(name) {
  return (process.env[name] ?? "").trim().replace(/^["']|["']$/g, "").trim();
}
function str(v) {
  return typeof v === "string" ? v : "";
}
var json = (status, body) => Response.json(body, { status });
function maxUsdc() {
  const configured = Number(env("BILLS_MAX_USDC"));
  return Number.isFinite(configured) && configured > 0 ? configured : DEFAULT_MAX_USDC;
}
function configProblem() {
  if (CHAIN_ID !== 5042) return "Bitrefill takes USDC on Base, so bills only work on the mainnet build";
  if (!env("BITREFILL_API_KEY")) return "BITREFILL_API_KEY is not set";
  return null;
}
var recent = /* @__PURE__ */ new Map();
var RATE_WINDOW_MS = 6e4;
var RATE_MAX = { products: 40, product: 40, invoices: 10, invoice: 40, phone: 10, preflight: 6 };
function rateLimited(route) {
  const now = Date.now();
  const hits = (recent.get(route) ?? []).filter((t) => now - t < RATE_WINDOW_MS);
  hits.push(now);
  recent.set(route, hits);
  return hits.length > (RATE_MAX[route] ?? 40);
}
var CACHE_MS = 10 * 6e4;
var catalogue = /* @__PURE__ */ new Map();
async function bitrefill(path, init) {
  const headers = new Headers(init?.headers);
  headers.set("accept", "application/json");
  headers.set("authorization", `Bearer ${env("BITREFILL_API_KEY")}`);
  if (init?.body) headers.set("content-type", "application/json");
  const res = await fetch(`${API}${path}`, { ...init, headers });
  const body = await res.json().catch(() => ({}));
  return { status: res.status, body };
}
function problemText(body, status) {
  return str(body.message) || str(body.error) || `Bitrefill returned ${status}`;
}
var PRODUCT_ID = /^[A-Za-z0-9][\w.-]{1,80}$/;
var INVOICE_ID = /^[A-Za-z0-9-]{8,64}$/;
var RECIPIENT = /^(\+\d{6,20}|\d[\d-]{3,31})$/;
var VALUE = /^\d{1,9}(\.\d{1,2})?$/;
function toProduct(raw) {
  const p = raw;
  const id = str(p?.id);
  if (!id) return null;
  const packages = Array.isArray(p?.packages) ? p.packages : [];
  const range = p?.range;
  return {
    id,
    name: str(p?.name) || id,
    country: str(p?.country_code) || str(p?.country),
    currency: str(p?.currency),
    image: str(p?.image) || void 0,
    inStock: p?.in_stock !== false,
    recipientType: str(p?.recipient_type),
    type: str(p?.type),
    packages: packages.map((pkg) => {
      const o = pkg;
      return { id: str(o.id) || str(o.package_id), value: String(o.value ?? ""), price: typeof o.price === "number" ? o.price : void 0 };
    }).filter((pkg) => pkg.id !== ""),
    ...range && typeof range.min === "number" && typeof range.max === "number" ? {
      range: {
        min: range.min,
        max: range.max,
        step: typeof range.step === "number" ? range.step : 1,
        ...typeof range.price_rate === "number" ? { priceRate: range.price_rate } : {}
      }
    } : {}
  };
}
var DIAL_CODES = {
  NG: "234",
  KE: "254",
  GH: "233",
  UG: "256",
  TZ: "255",
  ZA: "27",
  US: "1",
  GB: "44"
};
function toE164(raw, country) {
  const trimmed = raw.trim();
  if (trimmed.startsWith("+")) return trimmed.replace(/[\s()-]/g, "");
  const digits = trimmed.replace(/\D/g, "");
  const code = DIAL_CODES[(country ?? "").toUpperCase()];
  if (!code || digits === "") return trimmed;
  if (digits.startsWith(code) && digits.length > code.length + 6) return `+${digits}`;
  return `+${code}${digits.replace(/^0+/, "")}`;
}
function invoiceProblem(payload) {
  const productId = str(payload?.productId).trim();
  const packageId = str(payload?.packageId).trim();
  const value = str(payload?.value).trim();
  const typed = str(payload?.recipient).trim();
  const country = str(payload?.country).toUpperCase();
  const phone = payload?.phone === true;
  const recipient = phone ? toE164(typed, country) : typed.startsWith("+") ? typed.replace(/[\s()-]/g, "") : typed.replace(/[\s()]/g, "");
  const refundAddress = str(payload?.refundAddress).trim();
  if (!PRODUCT_ID.test(productId)) return { problem: "Pick something to pay for." };
  if (!packageId && !value) return { problem: "Pick an amount." };
  if (value && !VALUE.test(value)) return { problem: "That amount is not a number we can use." };
  if (packageId && !packageId.startsWith(productId)) return { problem: "That amount does not belong to this product." };
  if (!RECIPIENT.test(recipient)) return { problem: "Check the phone or meter number." };
  if (!isAddress(refundAddress)) return { problem: "A refund address is required." };
  return {
    invoice: {
      productId,
      ...packageId ? { packageId } : {},
      ...value ? { value } : {},
      recipient,
      refundAddress,
      ...country ? { country } : {},
      ...phone ? { phone } : {}
    }
  };
}
function interpretPrice(raw) {
  const text = String(raw ?? "").trim();
  if (!/^\d+(\.\d+)?$/.test(text)) return null;
  const value = Number(text);
  if (!Number.isFinite(value) || value <= 0) return null;
  if (text.includes(".")) return { usdc: value, smallestUnit: false };
  return value >= 1e3 ? { usdc: value / 1e6, smallestUnit: true } : { usdc: value, smallestUnit: false };
}
async function fiatPerUsdc(currency) {
  try {
    const res = await fetch(`https://api.paycrest.io/v1/rates/USDC/1/${encodeURIComponent(currency)}`, {
      headers: { accept: "application/json" }
    });
    if (!res.ok) return null;
    const body = await res.json();
    const rate = Number(body.data);
    return Number.isFinite(rate) && rate > 0 ? rate : null;
  } catch {
    return null;
  }
}
function priceBand(usdc, fiatAmount, currency, rate) {
  if (rate == null || !Number.isFinite(fiatAmount) || fiatAmount <= 0 || !Number.isFinite(rate) || rate <= 0) return null;
  const expected = fiatAmount / rate;
  if (usdc > expected * 4) return `${usdc} USDC is far more than ${fiatAmount} ${currency} is worth (about ${expected.toFixed(4)} USDC)`;
  if (usdc < expected / 4) return `${usdc} USDC is far less than ${fiatAmount} ${currency} is worth (about ${expected.toFixed(4)} USDC)`;
  return null;
}
async function plausiblePrice(usdc, fiatAmount, currency) {
  if (!Number.isFinite(fiatAmount) || fiatAmount <= 0) return null;
  const rate = currency.toUpperCase() === "USD" ? 1 : await fiatPerUsdc(currency);
  return priceBand(usdc, fiatAmount, currency, rate);
}
function paymentProblem(invoice, max = maxUsdc()) {
  const data = invoice;
  const id = str(data?.id);
  const payment = data?.payment;
  const address = str(payment?.address);
  const currency = str(payment?.currency).toUpperCase();
  const quoted = `${str(payment?.price) || String(payment?.price ?? "?")} ${currency || "(no currency)"} by ${str(payment?.method) || "unknown method"}`;
  if (!id) return { problem: "the invoice has no id" };
  if (!isAddress(address)) return { problem: "the payment address is not an address" };
  const read = interpretPrice(payment?.price);
  if (!read) return { problem: `the invoice has no usable price (${quoted})` };
  if (currency && currency !== "USDC") return { problem: `the invoice is priced in ${quoted}, not USDC` };
  if (read.usdc > max) return { problem: `the invoice asks for ${read.usdc} USDC (${quoted}), above the ${max} USDC limit` };
  const price = read.usdc.toFixed(6).replace(/\.?0+$/, "");
  return { id, payment: { address, price, currency: currency || "USDC" } };
}
function classify(product) {
  const name = product.name.toLowerCase();
  if (/waec|jamb|neco|nabteb|exam|scratch card|result checker/.test(name)) return "exams";
  if (/dstv|gotv|startimes|showmax|decoder|\btv\b/.test(name)) return "tv";
  if (/electric|ikeja|eko |ekedc|aedc|phed|kedco|ibedc|bedc|eedc|kaedco|jos |yola|aba power|disco|meter/.test(name)) {
    return "electricity";
  }
  if (/\bdata\b|bundle|internet|broadband|spectranet|smile/.test(name)) return "data";
  if (product.recipientType === "phone_number") return "airtime";
  if (product.recipientType === "account") return "utilities";
  return null;
}
async function countryCatalogue(country) {
  const key = `country:${country}`;
  const hit = catalogue.get(key);
  if (hit && Date.now() - hit.at < CACHE_MS) return hit.body.products;
  const products = [];
  for (let page = 0; page < 6; page++) {
    const { status, body } = await bitrefill(`/products?country=${country}&limit=50&start=${page * 50}`);
    if (status !== 200) {
      if (page === 0) throw new Error(problemText(body, status));
      break;
    }
    const batch = (Array.isArray(body.data) ? body.data : []).map(toProduct).filter((p) => p != null && p.inStock);
    products.push(...batch);
    if (batch.length < 50) break;
  }
  products.sort((a, b) => a.name.localeCompare(b.name));
  catalogue.set(key, { at: Date.now(), body: { products } });
  return products;
}
async function billProducts(category, country) {
  if (!CATEGORIES[category]) throw new Error(`unknown category "${category}"`);
  const all = await countryCatalogue(country);
  const wanted = all.filter((p) => classify(p) === category || category === "electricity" && classify(p) === "utilities");
  return wanted;
}
async function phoneOperators(number, country) {
  const dialled = toE164(number, country);
  const { status, body } = await bitrefill(`/check_phone_number?phone_number=${encodeURIComponent(dialled)}`);
  if (status !== 200) return [];
  const data = body.data;
  const list = Array.isArray(data) ? data : data ? [data] : [];
  return list.map((o) => {
    const row = o;
    return { id: str(row.id), name: str(row.name) || str(row.id) };
  }).filter((o) => o.id !== "");
}
async function createInvoice(request) {
  const { status, body } = await bitrefill("/invoices", {
    method: "POST",
    body: JSON.stringify({
      products: [
        {
          product_id: request.productId,
          quantity: 1,
          ...request.packageId ? { package_id: request.packageId } : {},
          ...request.value ? { value: Number(request.value) } : {},
          // Bitrefill uses this field for the phone number and for the account or
          // meter number of a biller that needs one
          phone_number: request.recipient
        }
      ],
      payment_method: PAYMENT_METHOD,
      refund_address: request.refundAddress
    })
  });
  if (status !== 200 && status !== 201) {
    console.error("[bills] invoice failed", status, body.message ?? body.error);
    return { problem: problemText(body, status), status: status === 401 || status === 403 ? 503 : 400 };
  }
  const raw = body.data?.payment;
  console.info("[bills] invoice payment", JSON.stringify(raw));
  const verdict = paymentProblem(body.data);
  if ("problem" in verdict) {
    console.error(`[bills] unusable invoice: ${verdict.problem}`);
    return { problem: `Bitrefill returned an invoice we could not verify (${verdict.problem}). Nothing was sent.`, status: 502 };
  }
  const ordered = orderedFiat(body.data);
  if (ordered) {
    const off = await plausiblePrice(Number(verdict.payment.price), ordered.amount, ordered.currency);
    if (off) {
      console.error(`[bills] implausible price: ${off}`);
      return { problem: `Bitrefill's price doesn't match what was ordered (${off}). Nothing was sent.`, status: 502 };
    }
  }
  return { id: verdict.id, payment: verdict.payment, invoice: body.data };
}
function orderedFiat(invoice) {
  const orders = invoice?.orders;
  const first = Array.isArray(orders) ? orders[0] : void 0;
  const product = first?.product;
  const amount = Number(product?.value);
  const currency = str(product?.currency).toUpperCase();
  return Number.isFinite(amount) && amount > 0 && /^[A-Z]{3}$/.test(currency) ? { amount, currency } : null;
}
async function handleBills(route, request) {
  const url = new URL(request.url);
  const problem = configProblem();
  if (route === "info") {
    return json(200, {
      enabled: problem == null,
      ...problem ? { reason: problem } : {},
      network: "base",
      maxUsdc: maxUsdc(),
      categories: Object.keys(CATEGORIES)
    });
  }
  if (problem) {
    if (route === "invoices") console.error(`[bills] not configured: ${problem}`);
    return json(503, { error: "Bill payments are not configured on this server." });
  }
  if (rateLimited(route)) return json(429, { error: "Too many requests \u2014 try again in a minute." });
  if (route === "products") {
    const category = str(url.searchParams.get("category"));
    const country = str(url.searchParams.get("country")).toUpperCase();
    if (!CATEGORIES[category]) return json(400, { error: "unknown category" });
    if (!/^[A-Z]{2}$/.test(country)) return json(400, { error: "country must be a 2-letter code" });
    try {
      return json(200, { products: await billProducts(category, country) });
    } catch (err) {
      return json(502, { error: err instanceof Error ? err.message : "could not read the catalogue" });
    }
  }
  if (route === "product") {
    const id = str(url.searchParams.get("id"));
    if (!PRODUCT_ID.test(id)) return json(400, { error: "bad product id" });
    const { status, body } = await bitrefill(`/products/${encodeURIComponent(id)}`);
    const product = toProduct(body.data);
    if (status !== 200 || !product) return json(502, { error: problemText(body, status) });
    return json(200, { product });
  }
  if (route === "phone") {
    const country = str(url.searchParams.get("country")).toUpperCase();
    const number = toE164(str(url.searchParams.get("number")), country).replace(/[\s()-]/g, "");
    if (!/^\+?\d{7,15}$/.test(number)) return json(400, { error: "that does not look like a phone number" });
    const { status, body } = await bitrefill(`/check_phone_number?phone_number=${encodeURIComponent(number)}`);
    if (status !== 200) return json(status === 429 ? 429 : 502, { error: problemText(body, status) });
    const data = body.data;
    const list = Array.isArray(data) ? data : data ? [data] : [];
    const operators = list.map((o) => {
      const row = o;
      return { id: str(row.id), name: str(row.name) || str(row.id) };
    }).filter((o) => o.id !== "");
    const meta = body.meta;
    return json(200, { number: str(meta?.phone_number) || number, operators });
  }
  if (route === "preflight") {
    const country = (str(url.searchParams.get("country")) || "NG").toUpperCase();
    const category = str(url.searchParams.get("category")) || "airtime";
    const number = str(url.searchParams.get("number"));
    const refundAddress = str(url.searchParams.get("refundAddress"));
    const steps = [];
    const note = (step, ok, detail) => steps.push({ step, ok, detail });
    let products = [];
    try {
      products = await billProducts(category, country);
      note("catalogue", products.length > 0, `${products.length} products for ${category} in ${country}`);
    } catch (err) {
      note("catalogue", false, err instanceof Error ? err.message : "failed");
      return json(200, { steps, ready: false });
    }
    let product = products[0];
    if (number) {
      const operators = await phoneOperators(number, country);
      const matched = operators.map((o) => products.find((p) => p.id === o.id)).find(Boolean);
      note("operator", operators.length > 0, operators.length > 0 ? operators.map((o) => o.name).join(", ") : `no operator for ${number}`);
      if (matched) product = matched;
    }
    if (!product) return json(200, { steps, ready: false });
    note("product", true, `${product.name} (${product.currency}), ${product.packages.length} denominations`);
    const cheapest = [...product.packages].sort((a, b) => Number(a.value) - Number(b.value))[0];
    note("denomination", cheapest != null, cheapest ? `${cheapest.value} ${product.currency}` : "ranged product");
    if (!isAddress(refundAddress) || !number) {
      note("invoice", false, "pass ?number=<phone>&refundAddress=<0x\u2026> to quote a real invoice");
      return json(200, { steps, ready: false });
    }
    const created2 = await createInvoice({
      productId: product.id,
      ...cheapest ? { packageId: cheapest.id } : { value: String(product.range?.min ?? 1) },
      recipient: number,
      refundAddress,
      country,
      phone: category === "airtime" || category === "data"
    });
    if ("problem" in created2) {
      note("invoice", false, created2.problem);
      return json(200, { steps, ready: false });
    }
    note("invoice", true, `${created2.payment.price} USDC to ${created2.payment.address} (unpaid, expires on its own)`);
    note("bridge", true, `the app would bridge ${created2.payment.price} USDC plus the relayer fee from Arc`);
    return json(200, { steps, ready: true, invoice: created2.id, payment: created2.payment });
  }
  if (route === "invoice") {
    const id = str(url.searchParams.get("id"));
    if (!INVOICE_ID.test(id)) return json(400, { error: "bad invoice id" });
    const { status, body } = await bitrefill(`/invoices/${encodeURIComponent(id)}`);
    if (status !== 200) return json(502, { error: problemText(body, status) });
    return json(200, { invoice: body.data });
  }
  if (request.method !== "POST") return json(405, { error: "method not allowed" });
  const payload = await request.json().catch(() => null);
  const checked = invoiceProblem(payload);
  if ("problem" in checked) return json(400, { error: checked.problem });
  const created = await createInvoice(checked.invoice);
  if ("problem" in created) return json(created.status, { error: created.problem });
  return json(201, { invoice: created.invoice, payment: created.payment, id: created.id });
}
export {
  billProducts,
  classify,
  createInvoice,
  handleBills,
  interpretPrice,
  invoiceProblem,
  maxUsdc,
  orderedFiat,
  paymentProblem,
  phoneOperators,
  plausiblePrice,
  priceBand,
  toE164
};
