// GENERATED by scripts/build-agent-api.mjs from server/*.ts — do not edit.

// server/bills.ts
import { isAddress } from "viem";

// server/chain.ts
import { createPublicClient, createWalletClient, defineChain, fallback, http } from "viem";
import { privateKeyToAccount } from "viem/accounts";
var IS_MAINNET = (process.env.VITE_ARC_NETWORK ?? "").trim() === "mainnet";
var USDC = { symbol: "USDC", address: "0x3600000000000000000000000000000000000000", decimals: 6 };
var NETWORKS = {
  testnet: {
    chainId: 5042002,
    name: "Arc Testnet",
    explorer: "https://explorer.testnet.arc.io",
    rpcs: ["https://rpc.testnet.arc.io", "https://rpc.testnet.arc.network"],
    // Same registry as src/tokens.ts
    tokens: [USDC, { symbol: "EURC", address: "0x89B50855Aa3bE2F677cD6303Cec089B5F319D72a", decimals: 6 }],
    // Synthra — verified: router factory() matches, USDC/EURC pools funded
    swap: {
      venue: "Synthra",
      router: "0xA545bCB1Bd7985c59ea162aB1748A0803434C31b",
      quoter: "0x3Ce954107b1A675826B33bF23060Dd655e3758fE",
      feeTiers: [100, 500, 3e3, 1e4],
      slippageBps: 50n
    },
    arcNames: "0x578dbd5734f13bca66a1355cca296c07823892a2",
    betaMaxPerDay: null
  },
  mainnet: {
    chainId: 5042,
    name: "Arc",
    explorer: "https://explorer.arc.io",
    rpcs: [
      "https://rpc.mainnet.arc.io",
      "https://rpc.blockdaemon.mainnet.arc.io",
      "https://rpc.drpc.mainnet.arc.io",
      "https://rpc.quicknode.mainnet.arc.io"
    ],
    tokens: [USDC],
    // No verified USDC/EURC pools on mainnet yet — the swap tool is off
    swap: null,
    arcNames: "0xF2DCe7fe2864FDD899b12185c610C11d425200d9",
    // Unaudited vault holding real money: refuse vaults whose daily limit is above this
    // (whole tokens; same cap as BETA_MAX_PER_DAY in src/agent-config.ts)
    betaMaxPerDay: 50
  }
};
var NET = IS_MAINNET ? NETWORKS.mainnet : NETWORKS.testnet;
var CHAIN_ID = NET.chainId;
var NETWORK_NAME = NET.name;
var EXPLORER = NET.explorer;
var TOKENS = NET.tokens;
var SWAP = NET.swap;
var ARC_NAMES = NET.arcNames;
var BETA_MAX_PER_DAY = NET.betaMaxPerDay;
var arcChain = defineChain({
  id: CHAIN_ID,
  name: NETWORK_NAME,
  nativeCurrency: { name: "USDC", symbol: "USDC", decimals: 18 },
  rpcUrls: { default: { http: [...NET.rpcs] } }
});
var publicClient = createPublicClient({
  chain: arcChain,
  transport: fallback(arcChain.rpcUrls.default.http.map((u) => http(u, { retryCount: 2, timeout: 15e3 })))
});

// server/bills.ts
var API = "https://api.bitrefill.com/v2";
var PAYMENT_METHOD = "usdc_base";
var DEFAULT_MAX_USDC = 100;
var CATEGORIES = {
  airtime: "refill,Minutes,phone,Mobile",
  data: "data,Data,bundles",
  electricity: "Electricity,utility-bills,utility-bill,Utility",
  tv: "TV,dth,streaming",
  bills: "bills,bill,utility-bills,utility-bill,Utility,Electricity,TV,dth"
};
function env(name) {
  return (process.env[name] ?? "").trim().replace(/^["']|["']$/g, "").trim();
}
function str(v) {
  return typeof v === "string" ? v : "";
}
var json = (status, body) => Response.json(body, { status });
function maxUsdc() {
  const configured = Number(env("BILLS_MAX_USDC"));
  return Number.isFinite(configured) && configured > 0 ? configured : DEFAULT_MAX_USDC;
}
function configProblem() {
  if (CHAIN_ID !== 5042) return "Bitrefill takes USDC on Base, so bills only work on the mainnet build";
  if (!env("BITREFILL_API_KEY")) return "BITREFILL_API_KEY is not set";
  return null;
}
var recent = /* @__PURE__ */ new Map();
var RATE_WINDOW_MS = 6e4;
var RATE_MAX = { products: 40, product: 40, invoices: 10, invoice: 40, phone: 10 };
function rateLimited(route) {
  const now = Date.now();
  const hits = (recent.get(route) ?? []).filter((t) => now - t < RATE_WINDOW_MS);
  hits.push(now);
  recent.set(route, hits);
  return hits.length > (RATE_MAX[route] ?? 40);
}
var CACHE_MS = 10 * 6e4;
var catalogue = /* @__PURE__ */ new Map();
async function bitrefill(path, init) {
  const headers = new Headers(init?.headers);
  headers.set("accept", "application/json");
  headers.set("authorization", `Bearer ${env("BITREFILL_API_KEY")}`);
  if (init?.body) headers.set("content-type", "application/json");
  const res = await fetch(`${API}${path}`, { ...init, headers });
  const body = await res.json().catch(() => ({}));
  return { status: res.status, body };
}
function problemText(body, status) {
  return str(body.message) || str(body.error) || `Bitrefill returned ${status}`;
}
var PRODUCT_ID = /^[A-Za-z0-9][\w.-]{1,80}$/;
var INVOICE_ID = /^[A-Za-z0-9-]{8,64}$/;
var RECIPIENT = /^(\+\d{6,20}|\d[\d-]{3,31})$/;
var VALUE = /^\d{1,9}(\.\d{1,2})?$/;
function toProduct(raw) {
  const p = raw;
  const id = str(p?.id);
  if (!id) return null;
  const packages = Array.isArray(p?.packages) ? p.packages : [];
  const range = p?.range;
  return {
    id,
    name: str(p?.name) || id,
    country: str(p?.country_code) || str(p?.country),
    currency: str(p?.currency),
    image: str(p?.image) || void 0,
    inStock: p?.in_stock !== false,
    recipientType: str(p?.recipient_type),
    packages: packages.map((pkg) => {
      const o = pkg;
      return { id: str(o.id) || str(o.package_id), value: String(o.value ?? ""), price: typeof o.price === "number" ? o.price : void 0 };
    }).filter((pkg) => pkg.id !== ""),
    ...range && typeof range.min === "number" && typeof range.max === "number" ? {
      range: {
        min: range.min,
        max: range.max,
        step: typeof range.step === "number" ? range.step : 1,
        ...typeof range.price_rate === "number" ? { priceRate: range.price_rate } : {}
      }
    } : {}
  };
}
function invoiceProblem(payload) {
  const productId = str(payload?.productId).trim();
  const packageId = str(payload?.packageId).trim();
  const value = str(payload?.value).trim();
  const typed = str(payload?.recipient).trim();
  const recipient = typed.startsWith("+") ? typed.replace(/[\s()-]/g, "") : typed.replace(/[\s()]/g, "");
  const refundAddress = str(payload?.refundAddress).trim();
  if (!PRODUCT_ID.test(productId)) return { problem: "Pick something to pay for." };
  if (!packageId && !value) return { problem: "Pick an amount." };
  if (value && !VALUE.test(value)) return { problem: "That amount is not a number we can use." };
  if (packageId && !packageId.startsWith(productId)) return { problem: "That amount does not belong to this product." };
  if (!RECIPIENT.test(recipient)) return { problem: "Check the phone or meter number." };
  if (!isAddress(refundAddress)) return { problem: "A refund address is required." };
  return { invoice: { productId, ...packageId ? { packageId } : {}, ...value ? { value } : {}, recipient, refundAddress } };
}
function interpretPrice(raw) {
  const text = String(raw ?? "").trim();
  if (!/^\d+(\.\d+)?$/.test(text)) return null;
  const value = Number(text);
  if (!Number.isFinite(value) || value <= 0) return null;
  if (text.includes(".")) return { usdc: value, smallestUnit: false };
  return value >= 1e3 ? { usdc: value / 1e6, smallestUnit: true } : { usdc: value, smallestUnit: false };
}
async function fiatPerUsdc(currency) {
  try {
    const res = await fetch(`https://api.paycrest.io/v1/rates/USDC/1/${encodeURIComponent(currency)}`, {
      headers: { accept: "application/json" }
    });
    if (!res.ok) return null;
    const body = await res.json();
    const rate = Number(body.data);
    return Number.isFinite(rate) && rate > 0 ? rate : null;
  } catch {
    return null;
  }
}
async function plausiblePrice(usdc, fiatAmount, currency) {
  if (!Number.isFinite(fiatAmount) || fiatAmount <= 0) return null;
  const rate = currency.toUpperCase() === "USD" ? 1 : await fiatPerUsdc(currency);
  if (rate == null) return null;
  const expected = fiatAmount / rate;
  if (usdc > expected * 4) return `${usdc} USDC is far more than ${fiatAmount} ${currency} is worth (about ${expected.toFixed(4)} USDC)`;
  if (usdc < expected / 4) return `${usdc} USDC is far less than ${fiatAmount} ${currency} is worth (about ${expected.toFixed(4)} USDC)`;
  return null;
}
function paymentProblem(invoice, max = maxUsdc()) {
  const data = invoice;
  const id = str(data?.id);
  const payment = data?.payment;
  const address = str(payment?.address);
  const currency = str(payment?.currency).toUpperCase();
  const quoted = `${str(payment?.price) || String(payment?.price ?? "?")} ${currency || "(no currency)"} by ${str(payment?.method) || "unknown method"}`;
  if (!id) return { problem: "the invoice has no id" };
  if (!isAddress(address)) return { problem: "the payment address is not an address" };
  const read = interpretPrice(payment?.price);
  if (!read) return { problem: `the invoice has no usable price (${quoted})` };
  if (currency && currency !== "USDC") return { problem: `the invoice is priced in ${quoted}, not USDC` };
  if (read.usdc > max) return { problem: `the invoice asks for ${read.usdc} USDC (${quoted}), above the ${max} USDC limit` };
  const price = read.usdc.toFixed(6).replace(/\.?0+$/, "");
  return { id, payment: { address, price, currency: currency || "USDC" } };
}
async function billProducts(category, country) {
  const categories = CATEGORIES[category];
  if (!categories) throw new Error(`unknown category "${category}"`);
  const key = `${country}:${categories}`;
  const hit = catalogue.get(key);
  if (hit && Date.now() - hit.at < CACHE_MS) return hit.body.products;
  const { status, body } = await bitrefill(`/products?country=${country}&category=${encodeURIComponent(categories)}&limit=50`);
  if (status !== 200) throw new Error(problemText(body, status));
  const products = (Array.isArray(body.data) ? body.data : []).map(toProduct).filter((p) => p != null && p.inStock).sort((a, b) => a.name.localeCompare(b.name));
  catalogue.set(key, { at: Date.now(), body: { products } });
  return products;
}
async function phoneOperators(number) {
  const { status, body } = await bitrefill(`/check_phone_number?phone_number=${encodeURIComponent(number)}`);
  if (status !== 200) return [];
  const data = body.data;
  const list = Array.isArray(data) ? data : data ? [data] : [];
  return list.map((o) => {
    const row = o;
    return { id: str(row.id), name: str(row.name) || str(row.id) };
  }).filter((o) => o.id !== "");
}
async function createInvoice(request) {
  const { status, body } = await bitrefill("/invoices", {
    method: "POST",
    body: JSON.stringify({
      products: [
        {
          product_id: request.productId,
          quantity: 1,
          ...request.packageId ? { package_id: request.packageId } : {},
          ...request.value ? { value: Number(request.value) } : {},
          // Bitrefill uses this field for the phone number and for the account or
          // meter number of a biller that needs one
          phone_number: request.recipient
        }
      ],
      payment_method: PAYMENT_METHOD,
      refund_address: request.refundAddress
    })
  });
  if (status !== 200 && status !== 201) {
    console.error("[bills] invoice failed", status, body.message ?? body.error);
    return { problem: problemText(body, status), status: status === 401 || status === 403 ? 503 : 400 };
  }
  const raw = body.data?.payment;
  console.info("[bills] invoice payment", JSON.stringify(raw));
  const verdict = paymentProblem(body.data);
  if ("problem" in verdict) {
    console.error(`[bills] unusable invoice: ${verdict.problem}`);
    return { problem: `Bitrefill returned an invoice we could not verify (${verdict.problem}). Nothing was sent.`, status: 502 };
  }
  return { id: verdict.id, payment: verdict.payment, invoice: body.data };
}
async function handleBills(route, request) {
  const url = new URL(request.url);
  const problem = configProblem();
  if (route === "info") {
    return json(200, {
      enabled: problem == null,
      ...problem ? { reason: problem } : {},
      network: "base",
      maxUsdc: maxUsdc(),
      categories: Object.keys(CATEGORIES)
    });
  }
  if (problem) {
    if (route === "invoices") console.error(`[bills] not configured: ${problem}`);
    return json(503, { error: "Bill payments are not configured on this server." });
  }
  if (rateLimited(route)) return json(429, { error: "Too many requests \u2014 try again in a minute." });
  if (route === "products") {
    const category = CATEGORIES[str(url.searchParams.get("category"))];
    const country = str(url.searchParams.get("country")).toUpperCase();
    if (!category) return json(400, { error: "unknown category" });
    if (!/^[A-Z]{2}$/.test(country)) return json(400, { error: "country must be a 2-letter code" });
    const key = `${country}:${category}`;
    const hit = catalogue.get(key);
    if (hit && Date.now() - hit.at < CACHE_MS) return json(200, hit.body);
    const { status, body } = await bitrefill(`/products?country=${country}&category=${encodeURIComponent(category)}&limit=50`);
    if (status !== 200) return json(status === 401 ? 503 : 502, { error: problemText(body, status) });
    const products = (Array.isArray(body.data) ? body.data : []).map(toProduct).filter((p) => p != null && p.inStock).sort((a, b) => a.name.localeCompare(b.name));
    const payload2 = { products };
    catalogue.set(key, { at: Date.now(), body: payload2 });
    return json(200, payload2);
  }
  if (route === "product") {
    const id = str(url.searchParams.get("id"));
    if (!PRODUCT_ID.test(id)) return json(400, { error: "bad product id" });
    const { status, body } = await bitrefill(`/products/${encodeURIComponent(id)}`);
    const product = toProduct(body.data);
    if (status !== 200 || !product) return json(502, { error: problemText(body, status) });
    return json(200, { product });
  }
  if (route === "phone") {
    const number = str(url.searchParams.get("number")).replace(/[\s()-]/g, "");
    if (!/^\+?\d{7,15}$/.test(number)) return json(400, { error: "that does not look like a phone number" });
    const { status, body } = await bitrefill(`/check_phone_number?phone_number=${encodeURIComponent(number)}`);
    if (status !== 200) return json(status === 429 ? 429 : 502, { error: problemText(body, status) });
    const data = body.data;
    const list = Array.isArray(data) ? data : data ? [data] : [];
    const operators = list.map((o) => {
      const row = o;
      return { id: str(row.id), name: str(row.name) || str(row.id) };
    }).filter((o) => o.id !== "");
    const meta = body.meta;
    return json(200, { number: str(meta?.phone_number) || number, operators });
  }
  if (route === "invoice") {
    const id = str(url.searchParams.get("id"));
    if (!INVOICE_ID.test(id)) return json(400, { error: "bad invoice id" });
    const { status, body } = await bitrefill(`/invoices/${encodeURIComponent(id)}`);
    if (status !== 200) return json(502, { error: problemText(body, status) });
    return json(200, { invoice: body.data });
  }
  if (request.method !== "POST") return json(405, { error: "method not allowed" });
  const payload = await request.json().catch(() => null);
  const checked = invoiceProblem(payload);
  if ("problem" in checked) return json(400, { error: checked.problem });
  const created = await createInvoice(checked.invoice);
  if ("problem" in created) return json(created.status, { error: created.problem });
  return json(201, { invoice: created.invoice, payment: created.payment, id: created.id });
}
export {
  billProducts,
  createInvoice,
  handleBills,
  interpretPrice,
  invoiceProblem,
  maxUsdc,
  paymentProblem,
  phoneOperators,
  plausiblePrice
};
