// GENERATED by scripts/build-agent-api.mjs from server/*.ts — do not edit.

// server/gasless.ts
import { getAddress, isAddress, isHex, verifyTypedData } from "viem";
import { generatePrivateKey, privateKeyToAccount as privateKeyToAccount2 } from "viem/accounts";

// server/chain.ts
import { createPublicClient, createWalletClient, defineChain, fallback, http } from "viem";
import { privateKeyToAccount } from "viem/accounts";
var IS_MAINNET = (process.env.VITE_ARC_NETWORK ?? "").trim() === "mainnet";
var USDC = { symbol: "USDC", address: "0x3600000000000000000000000000000000000000", decimals: 6 };
var NETWORKS = {
  testnet: {
    chainId: 5042002,
    name: "Arc Testnet",
    explorer: "https://explorer.testnet.arc.io",
    rpcs: ["https://rpc.testnet.arc.io", "https://rpc.testnet.arc.network"],
    // Same registry as src/tokens.ts
    tokens: [USDC, { symbol: "EURC", address: "0x89B50855Aa3bE2F677cD6303Cec089B5F319D72a", decimals: 6 }],
    // Synthra — verified: router factory() matches, USDC/EURC pools funded
    swap: {
      venue: "Synthra",
      router: "0xA545bCB1Bd7985c59ea162aB1748A0803434C31b",
      quoter: "0x3Ce954107b1A675826B33bF23060Dd655e3758fE",
      feeTiers: [100, 500, 3e3, 1e4],
      slippageBps: 50n
    },
    arcNames: "0x578dbd5734f13bca66a1355cca296c07823892a2",
    betaMaxPerDay: null
  },
  mainnet: {
    chainId: 5042,
    name: "Arc",
    explorer: "https://explorer.arc.io",
    rpcs: [
      "https://rpc.mainnet.arc.io",
      "https://rpc.blockdaemon.mainnet.arc.io",
      "https://rpc.drpc.mainnet.arc.io",
      "https://rpc.quicknode.mainnet.arc.io"
    ],
    tokens: [USDC],
    // No verified USDC/EURC pools on mainnet yet — the swap tool is off
    swap: null,
    arcNames: "0xF2DCe7fe2864FDD899b12185c610C11d425200d9",
    // Unaudited vault holding real money: refuse vaults whose daily limit is above this
    // (whole tokens; same cap as BETA_MAX_PER_DAY in src/agent-config.ts)
    betaMaxPerDay: 50
  }
};
var NET = IS_MAINNET ? NETWORKS.mainnet : NETWORKS.testnet;
var CHAIN_ID = NET.chainId;
var NETWORK_NAME = NET.name;
var EXPLORER = NET.explorer;
var TOKENS = NET.tokens;
var SWAP = NET.swap;
var ARC_NAMES = NET.arcNames;
var BETA_MAX_PER_DAY = NET.betaMaxPerDay;
var arcChain = defineChain({
  id: CHAIN_ID,
  name: NETWORK_NAME,
  nativeCurrency: { name: "USDC", symbol: "USDC", decimals: 18 },
  rpcUrls: { default: { http: [...NET.rpcs] } }
});
var publicClient = createPublicClient({
  chain: arcChain,
  transport: fallback(arcChain.rpcUrls.default.http.map((u) => http(u, { retryCount: 2, timeout: 15e3 })))
});

// server/gasless.ts
var USDC2 = "0x3600000000000000000000000000000000000000";
var NETWORK = `eip155:${CHAIN_ID}`;
var DEFAULT_API = "https://api.circle.com";
var USDC_DOMAIN = { name: "USDC", version: "2", chainId: CHAIN_ID, verifyingContract: USDC2 };
var TRANSFER_WITH_AUTHORIZATION_TYPES = {
  TransferWithAuthorization: [
    { name: "from", type: "address" },
    { name: "to", type: "address" },
    { name: "value", type: "uint256" },
    { name: "validAfter", type: "uint256" },
    { name: "validBefore", type: "uint256" },
    { name: "nonce", type: "bytes32" }
  ]
};
var authorizationStateAbi = [
  {
    type: "function",
    name: "authorizationState",
    stateMutability: "view",
    inputs: [
      { name: "authorizer", type: "address" },
      { name: "nonce", type: "bytes32" }
    ],
    outputs: [{ type: "bool" }]
  }
];
var MAX_VALIDITY_S = 30 * 60;
var MIN_VALIDITY_S = 60;
var SETTLE_WAIT_S = 20;
function env(name) {
  return (process.env[name] ?? "").trim().replace(/^["']|["']$/g, "").trim();
}
function configProblem() {
  const key = env("CIRCLE_API_KEY");
  if (!key) return "CIRCLE_API_KEY is not set";
  const testnet = CHAIN_ID !== 5042;
  if (testnet && key.startsWith("LIVE_API_KEY:")) return "CIRCLE_API_KEY is a mainnet (LIVE) key but the app is on Arc Testnet";
  if (!testnet && key.startsWith("TEST_API_KEY:")) return "CIRCLE_API_KEY is a testnet (TEST) key but the app is on Arc mainnet";
  return null;
}
var json = (status, body) => Response.json(body, { status });
function str(v) {
  return typeof v === "string" ? v : "";
}
var recent = /* @__PURE__ */ new Map();
var RATE_WINDOW_MS = 6e4;
var RATE_MAX = 5;
function parseAuthorization(raw) {
  if (!raw || typeof raw !== "object") return "authorization is required";
  const a = raw;
  const from = str(a.from);
  const to = str(a.to);
  const nonce = str(a.nonce);
  if (!isAddress(from) || !isAddress(to)) return "invalid address";
  if (!isHex(nonce) || nonce.length !== 66) return "invalid nonce";
  let value, validAfter, validBefore;
  try {
    value = BigInt(str(a.value));
    validAfter = BigInt(str(a.validAfter));
    validBefore = BigInt(str(a.validBefore));
  } catch {
    return "invalid number";
  }
  if (value <= 0n) return "amount must be above 0";
  if (getAddress(from) === getAddress(to)) return "sender and recipient are the same";
  return { from: getAddress(from), to: getAddress(to), value, validAfter, validBefore, nonce };
}
async function handleGasless(route, request) {
  const problem = configProblem();
  if (route === "info" && request.method === "GET") {
    return json(200, { enabled: problem == null, chainId: CHAIN_ID, ...problem ? { reason: problem } : {} });
  }
  if (route === "check" && request.method === "GET") {
    if (problem) return json(200, { ok: false, reason: problem });
    return json(200, await diagnose());
  }
  if (route !== "settle" || request.method !== "POST") return json(405, { error: "method not allowed" });
  if (problem) {
    console.error(`[gasless] misconfigured: ${problem}`);
    return json(503, { status: "rejected", reason: "Gasless sends are not configured on this server." });
  }
  try {
    const text = await request.text();
    if (text.length > 5e3) return json(413, { status: "rejected", reason: "body too large" });
    const body = text ? JSON.parse(text) : {};
    const auth = parseAuthorization(body.authorization);
    const signature = str(body.signature);
    if (typeof auth === "string") return json(400, { status: "rejected", reason: auth });
    if (!isHex(signature)) return json(400, { status: "rejected", reason: "invalid signature" });
    const now = BigInt(Math.floor(Date.now() / 1e3));
    if (auth.validAfter > now) return json(400, { status: "rejected", reason: "authorization is not valid yet" });
    if (auth.validBefore < now + BigInt(MIN_VALIDITY_S) || auth.validBefore > now + BigInt(MAX_VALIDITY_S)) {
      return json(400, { status: "rejected", reason: `authorization must expire within ${MAX_VALIDITY_S / 60} minutes` });
    }
    const valid = await verifyTypedData({
      address: auth.from,
      domain: USDC_DOMAIN,
      types: TRANSFER_WITH_AUTHORIZATION_TYPES,
      primaryType: "TransferWithAuthorization",
      message: auth,
      signature
    });
    if (!valid) return json(400, { status: "rejected", reason: "the signature does not match the sender" });
    const times = (recent.get(auth.from) ?? []).filter((t) => Date.now() - t < RATE_WINDOW_MS);
    if (times.length >= RATE_MAX) return json(429, { status: "rejected", reason: "Too many gasless sends \u2014 wait a minute." });
    recent.set(auth.from, [...times, Date.now()]);
    const used = await publicClient.readContract({ address: USDC2, abi: authorizationStateAbi, functionName: "authorizationState", args: [auth.from, auth.nonce] }).catch(() => false);
    if (used) return json(200, { status: "pending", reason: "this authorization was already settled" });
    try {
      return json(200, await settle(auth, signature, new URL(request.url).origin));
    } catch (err) {
      console.error("[gasless] settle failed", err);
      return json(502, { status: "pending", reason: "Circle did not answer cleanly" });
    }
  } catch (err) {
    console.error("[gasless] bad request", err);
    return json(400, { status: "rejected", reason: "bad request" });
  }
}
async function diagnose() {
  const api = env("CIRCLE_FACILITATOR_URL") || DEFAULT_API;
  const headers = { "content-type": "application/json", authorization: `Bearer ${env("CIRCLE_API_KEY")}` };
  const short = (v) => JSON.stringify(v).slice(0, 300);
  const keyCheck = await fetch(`${api}/v1/w3s/wallets`, { headers, signal: AbortSignal.timeout(15e3) }).then(async (r) => ({ status: r.status, body: short(await r.json().catch(() => null)) })).catch((e) => ({ status: 0, body: e.message.slice(0, 200) }));
  const buyer = privateKeyToAccount2(generatePrivateKey());
  const payTo = privateKeyToAccount2(generatePrivateKey()).address;
  const nonce = "0x" + Buffer.from(crypto.getRandomValues(new Uint8Array(32))).toString("hex");
  const auth = {
    from: buyer.address,
    to: payTo,
    value: 10000n,
    validAfter: 0n,
    validBefore: BigInt(Math.floor(Date.now() / 1e3) + 600),
    nonce
  };
  const signature = await buyer.signTypedData({
    domain: USDC_DOMAIN,
    types: TRANSFER_WITH_AUTHORIZATION_TYPES,
    primaryType: "TransferWithAuthorization",
    message: auth
  });
  const probe = await fetch(`${api}/v1/facilitator/x402/settle`, {
    method: "POST",
    headers,
    body: JSON.stringify(settleBody(auth, signature, "https://vlora-two.vercel.app")),
    signal: AbortSignal.timeout(4e4)
  }).then(async (r) => ({ status: r.status, body: short(await r.json().catch(() => null)) })).catch((e) => ({ status: 0, body: e.message.slice(0, 200) }));
  const verdict = probe.status === 200 ? "The API key can settle on this network. A refusal of a real payment is about that payment (recipient, amount or screening), not the key." : probe.status === 401 ? "Circle rejected the API key itself (401). Check CIRCLE_API_KEY, and that it is a LIVE key on mainnet." : probe.status === 403 ? "Circle refuses to settle for this key (403) even for a throwaway payment: the account/key is not enabled for Facilitator Service on this network." : `Unexpected response from Circle (${probe.status}).`;
  return { network: NETWORK, keyCheck, settleProbe: probe, verdict };
}
function settleBody(auth, signature, origin) {
  const value = auth.value.toString();
  const requirements = {
    scheme: "exact",
    network: NETWORK,
    amount: value,
    asset: USDC2,
    payTo: auth.to,
    maxTimeoutSeconds: SETTLE_WAIT_S,
    extra: { name: "USDC", version: "2" }
  };
  return {
    x402Version: 2,
    paymentPayload: {
      x402Version: 2,
      resource: { url: `${origin}/send`, description: "Vlora USDC payment", mimeType: "application/json" },
      accepted: { ...requirements, extra: { ...requirements.extra, assetTransferMethod: "eip3009" } },
      payload: {
        signature,
        authorization: {
          from: auth.from,
          to: auth.to,
          value,
          validAfter: auth.validAfter.toString(),
          validBefore: auth.validBefore.toString(),
          nonce: auth.nonce
        }
      },
      // Derived from the EIP-3009 nonce, so a retry of the same signature converges on one payment
      extensions: { "payment-identifier": { info: { required: true, id: `vlora_${auth.nonce.slice(2, 42)}` } } }
    },
    paymentRequirements: requirements
  };
}
async function settle(auth, signature, origin) {
  const api = env("CIRCLE_FACILITATOR_URL") || DEFAULT_API;
  const payload = settleBody(auth, signature, origin);
  const res = await fetch(`${api}/v1/facilitator/x402/settle`, {
    method: "POST",
    headers: { "content-type": "application/json", authorization: `Bearer ${env("CIRCLE_API_KEY")}` },
    body: JSON.stringify(payload),
    signal: AbortSignal.timeout((SETTLE_WAIT_S + 15) * 1e3)
  });
  const data = await res.json().catch(() => ({}));
  if (res.status !== 200) {
    console.error(`[gasless] Circle ${res.status}: ${JSON.stringify(data).slice(0, 800)}`);
    if (res.status >= 500 || res.status === 409) return { status: "pending", reason: `Circle error ${res.status}` };
    const details = circleErrorDetails(data.errors);
    return {
      status: "rejected",
      reason: `${circleReason(res.status, data.message)}${details ? ` \u2014 ${details}` : ""}`,
      // A policy refusal (403) or bad key (401) won't change by retrying: the client stops offering gasless
      ...res.status === 401 || res.status === 403 ? { disable: true } : {}
    };
  }
  if (data.success && data.transaction && isHex(data.transaction)) return { status: "success", transaction: data.transaction };
  const recorded = data.extensions?.["settlement-status"];
  if (data.errorReason === "settlement_pending" || recorded?.status === "pending") {
    const paymentId = recorded?.paymentId;
    if (paymentId) {
      const tx = await pollStatus(api, paymentId);
      if (tx) return { status: "success", transaction: tx };
    }
    return { status: "pending", reason: "Circle is still settling it" };
  }
  return { status: "rejected", reason: settleReason(data.errorReason) };
}
async function pollStatus(api, paymentId) {
  for (let i = 0; i < 5; i++) {
    await new Promise((r) => setTimeout(r, 3e3));
    try {
      const res = await fetch(`${api}/v1/facilitator/x402/status/${encodeURIComponent(paymentId)}`, {
        headers: { authorization: `Bearer ${env("CIRCLE_API_KEY")}` },
        signal: AbortSignal.timeout(1e4)
      });
      const data = await res.json();
      if (data.status === "completed" && data.transaction && isHex(data.transaction)) return data.transaction;
      if (data.status === "failed") return null;
    } catch {
    }
  }
  return null;
}
function circleErrorDetails(errors) {
  if (!Array.isArray(errors)) return "";
  return errors.map((e) => {
    if (typeof e === "string") return e;
    if (e && typeof e === "object") {
      const o = e;
      const text = [o.code, o.error, o.message, o.location ?? o.field].filter((v) => typeof v === "string" || typeof v === "number");
      return text.length ? text.join(" ") : JSON.stringify(o);
    }
    return "";
  }).filter(Boolean).join("; ").slice(0, 300);
}
function circleReason(status, message) {
  if (status === 401) return "Circle rejected the API key";
  if (status === 403) {
    return `Circle refused to settle for this API key (${message ?? "forbidden"}). Check in Circle Console that the key has Facilitator access on Arc mainnet`;
  }
  if (status === 429) return "Circle rate limit \u2014 try again in a minute";
  return message ?? `Circle rejected the request (${status})`;
}
function settleReason(code) {
  switch (code) {
    case "insufficient_funds":
      return "not enough USDC";
    case "invalid_exact_evm_payload_signature":
      return "Circle could not verify the signature";
    case "invalid_exact_evm_payload_authorization_valid_before":
      return "the authorization expired";
    case "invalid_network":
      return "Circle does not support this network for your key";
    case void 0:
      return "Circle could not settle it";
    default:
      return `Circle: ${code}`;
  }
}
export {
  TRANSFER_WITH_AUTHORIZATION_TYPES,
  USDC_DOMAIN,
  handleGasless
};
