// GENERATED by scripts/build-agent-api.mjs from server/*.ts — do not edit.

// server/offramp.ts
import { isAddress } from "viem";

// server/chain.ts
import { createPublicClient, createWalletClient, defineChain, fallback, http } from "viem";
import { privateKeyToAccount } from "viem/accounts";
var IS_MAINNET = (process.env.VITE_ARC_NETWORK ?? "").trim() === "mainnet";
var USDC = { symbol: "USDC", address: "0x3600000000000000000000000000000000000000", decimals: 6 };
var NETWORKS = {
  testnet: {
    chainId: 5042002,
    name: "Arc Testnet",
    explorer: "https://explorer.testnet.arc.io",
    rpcs: ["https://rpc.testnet.arc.io", "https://rpc.testnet.arc.network"],
    // Same registry as src/tokens.ts
    tokens: [USDC, { symbol: "EURC", address: "0x89B50855Aa3bE2F677cD6303Cec089B5F319D72a", decimals: 6 }],
    // Synthra — verified: router factory() matches, USDC/EURC pools funded
    swap: {
      venue: "Synthra",
      router: "0xA545bCB1Bd7985c59ea162aB1748A0803434C31b",
      quoter: "0x3Ce954107b1A675826B33bF23060Dd655e3758fE",
      feeTiers: [100, 500, 3e3, 1e4],
      slippageBps: 50n
    },
    arcNames: "0x578dbd5734f13bca66a1355cca296c07823892a2",
    betaMaxPerDay: null
  },
  mainnet: {
    chainId: 5042,
    name: "Arc",
    explorer: "https://explorer.arc.io",
    rpcs: [
      "https://rpc.mainnet.arc.io",
      "https://rpc.blockdaemon.mainnet.arc.io",
      "https://rpc.drpc.mainnet.arc.io",
      "https://rpc.quicknode.mainnet.arc.io"
    ],
    tokens: [USDC],
    // No verified USDC/EURC pools on mainnet yet — the swap tool is off
    swap: null,
    arcNames: "0xF2DCe7fe2864FDD899b12185c610C11d425200d9",
    // Unaudited vault holding real money: refuse vaults whose daily limit is above this
    // (whole tokens; same cap as BETA_MAX_PER_DAY in src/agent-config.ts)
    betaMaxPerDay: 50
  }
};
var NET = IS_MAINNET ? NETWORKS.mainnet : NETWORKS.testnet;
var CHAIN_ID = NET.chainId;
var NETWORK_NAME = NET.name;
var EXPLORER = NET.explorer;
var TOKENS = NET.tokens;
var SWAP = NET.swap;
var ARC_NAMES = NET.arcNames;
var BETA_MAX_PER_DAY = NET.betaMaxPerDay;
var arcChain = defineChain({
  id: CHAIN_ID,
  name: NETWORK_NAME,
  nativeCurrency: { name: "USDC", symbol: "USDC", decimals: 18 },
  rpcUrls: { default: { http: [...NET.rpcs] } }
});
var publicClient = createPublicClient({
  chain: arcChain,
  transport: fallback(arcChain.rpcUrls.default.http.map((u) => http(u, { retryCount: 2, timeout: 15e3 })))
});

// server/offramp.ts
var API = "https://api.paycrest.io/v2";
var NETWORK = "base";
var TOKEN = "USDC";
var MIN_USDC = 1;
var DEFAULT_MAX_USDC = 100;
function env(name) {
  return (process.env[name] ?? "").trim().replace(/^["']|["']$/g, "").trim();
}
function str(v) {
  return typeof v === "string" ? v : "";
}
var json = (status, body) => Response.json(body, { status });
function maxUsdc() {
  const configured = Number(env("OFFRAMP_MAX_USDC"));
  return Number.isFinite(configured) && configured > 0 ? configured : DEFAULT_MAX_USDC;
}
function configProblem() {
  if (CHAIN_ID !== 5042) return "Paycrest settles on mainnet only, and this app is on Arc Testnet";
  if (!env("PAYCREST_API_KEY")) return "PAYCREST_API_KEY is not set";
  return null;
}
var recent = /* @__PURE__ */ new Map();
var RATE_WINDOW_MS = 6e4;
var RATE_MAX = { verify: 30, orders: 10, deposits: 10, rate: 120, institutions: 60, order: 120 };
function rateLimited(route) {
  const now = Date.now();
  const hits = (recent.get(route) ?? []).filter((t) => now - t < RATE_WINDOW_MS);
  hits.push(now);
  recent.set(route, hits);
  return hits.length > (RATE_MAX[route] ?? 60);
}
async function paycrest(path, init) {
  const headers = new Headers(init?.headers);
  headers.set("accept", "application/json");
  if (init?.body) headers.set("content-type", "application/json");
  if (init?.authenticated) headers.set("API-Key", env("PAYCREST_API_KEY"));
  const res = await fetch(`${API}${path}`, { ...init, headers });
  const body = await res.json().catch(() => ({}));
  return { status: res.status, body };
}
function problemText(body) {
  const fields = Array.isArray(body.data) ? body.data : body.data && typeof body.data === "object" ? [body.data] : [];
  const details = fields.map((f) => {
    const o = f;
    return [str(o.field), str(o.message)].filter(Boolean).join(": ");
  }).filter(Boolean).join("; ");
  return [str(body.message), details].filter(Boolean).join(" \u2014 ") || "Paycrest rejected the request";
}
var CURRENCY = /^[A-Z]{3}$/;
var INSTITUTION = /^[A-Z0-9]{3,24}$/;
var ACCOUNT = /^[A-Za-z0-9|+-]{5,40}$/;
var PROVIDER_ID = /^[A-Za-z0-9]{4,24}$/;
var AMOUNT = /^\d{1,7}(\.\d{1,6})?$/;
function cleanAmount(raw, max = maxUsdc()) {
  const value = str(raw).trim();
  if (!AMOUNT.test(value)) return null;
  const n = Number(value);
  if (!Number.isFinite(n) || n < MIN_USDC || n > max) return null;
  return value;
}
function orderProblem(payload, max = maxUsdc()) {
  const amount = cleanAmount(payload?.amount, max);
  const currency = str(payload?.currency).toUpperCase();
  const institution = str(payload?.institution).toUpperCase();
  const accountIdentifier = str(payload?.accountIdentifier).trim();
  const accountName = str(payload?.accountName).trim();
  const memo = str(payload?.memo).trim().slice(0, 100);
  const refundAddress = str(payload?.refundAddress).trim();
  const providerIds = (Array.isArray(payload?.providerIds) ? payload.providerIds : []).map((id) => str(id)).filter((id) => PROVIDER_ID.test(id)).slice(0, 3);
  if (!amount) return { problem: `Amount must be between ${MIN_USDC} and ${max} USDC.` };
  if (!CURRENCY.test(currency)) return { problem: "Pick a currency." };
  if (!INSTITUTION.test(institution)) return { problem: "Pick a bank." };
  if (!ACCOUNT.test(accountIdentifier)) return { problem: "That account number looks wrong." };
  if (accountName.length < 2 || accountName.length > 100) return { problem: "Account name is missing." };
  if (!isAddress(refundAddress)) return { problem: "A refund address is required." };
  return { order: { amount, currency, institution, accountIdentifier, accountName, memo, refundAddress, providerIds } };
}
function depositProblem(order) {
  const data = order;
  const account = data?.providerAccount;
  if (!str(data?.id)) return "the order has no id";
  if (!account || str(account.network) !== NETWORK) return `the deposit is not on ${NETWORK}`;
  if (!isAddress(str(account.receiveAddress))) return "the deposit address is not an address";
  return null;
}
async function handleOfframp(route, request) {
  const url = new URL(request.url);
  const problem = configProblem();
  if (route === "info") {
    const currencies = await paycrest("/currencies");
    return json(200, {
      enabled: problem == null,
      ...problem ? { reason: problem } : {},
      network: NETWORK,
      token: TOKEN,
      minUsdc: MIN_USDC,
      maxUsdc: maxUsdc(),
      currencies: Array.isArray(currencies.body.data) ? currencies.body.data : []
    });
  }
  if (rateLimited(route)) return json(429, { error: "Too many requests \u2014 try again in a minute." });
  if (route === "institutions") {
    const currency2 = url.searchParams.get("currency") ?? "";
    if (!CURRENCY.test(currency2)) return json(400, { error: "currency must be a 3-letter code" });
    const { status: status2, body: body2 } = await paycrest(`/institutions/${currency2}`);
    return status2 === 200 ? json(200, { institutions: body2.data ?? [] }) : json(502, { error: problemText(body2) });
  }
  if (route === "rate") {
    const currency2 = url.searchParams.get("currency") ?? "";
    const amount2 = cleanAmount(url.searchParams.get("amount") ?? "");
    if (!CURRENCY.test(currency2)) return json(400, { error: "currency must be a 3-letter code" });
    if (!amount2) return json(400, { error: `amount must be between ${MIN_USDC} and ${maxUsdc()} USDC` });
    const { status: status2, body: body2 } = await paycrest(`/rates/${NETWORK}/${TOKEN}/${amount2}/${currency2}?side=sell`);
    const sell = body2.data?.sell;
    if (status2 !== 200 || !sell?.rate) return json(502, { error: problemText(body2) });
    return json(200, { rate: sell.rate, providerIds: sell.providerIds ?? [], currency: currency2, amount: amount2 });
  }
  if (route === "verify") {
    if (request.method !== "POST") return json(405, { error: "method not allowed" });
    const payload2 = await request.json().catch(() => null);
    const institution2 = str(payload2?.institution).toUpperCase();
    const accountIdentifier2 = str(payload2?.accountIdentifier).trim();
    if (!INSTITUTION.test(institution2)) return json(400, { error: "institution is not a valid code" });
    if (!ACCOUNT.test(accountIdentifier2)) return json(400, { error: "account number looks wrong" });
    const { status: status2, body: body2 } = await paycrest("/verify-account", {
      method: "POST",
      body: JSON.stringify({ institution: institution2, accountIdentifier: accountIdentifier2 })
    });
    if (status2 !== 200) return json(400, { error: problemText(body2) });
    return json(200, { accountName: str(body2.data) });
  }
  if (route === "deposits") {
    if (request.method !== "POST") return json(405, { error: "method not allowed" });
    if (problem) {
      console.error(`[offramp] not configured: ${problem}`);
      return json(503, { error: "Bank deposits are not configured on this server." });
    }
    const payload2 = await request.json().catch(() => null);
    const amount2 = str(payload2?.amount).trim();
    const currency2 = str(payload2?.currency).toUpperCase();
    const recipient = str(payload2?.recipient).trim();
    const institution2 = str(payload2?.institution).toUpperCase();
    const accountIdentifier2 = str(payload2?.accountIdentifier).trim();
    const accountName2 = str(payload2?.accountName).trim();
    if (!/^\d{2,9}(\.\d{1,2})?$/.test(amount2)) return json(400, { error: "Enter how much you want to pay in." });
    if (!CURRENCY.test(currency2)) return json(400, { error: "Pick a currency." });
    if (!isAddress(recipient)) return json(400, { error: "A wallet address is required." });
    if (!INSTITUTION.test(institution2)) return json(400, { error: "Pick the bank you are paying from." });
    if (!ACCOUNT.test(accountIdentifier2)) return json(400, { error: "That account number looks wrong." });
    if (accountName2.length < 2 || accountName2.length > 100) return json(400, { error: "Account name is missing." });
    const { status: status2, body: body2 } = await paycrest("/sender/orders", {
      method: "POST",
      authenticated: true,
      body: JSON.stringify({
        amount: amount2,
        amountIn: "fiat",
        source: { type: "fiat", currency: currency2, refundAccount: { institution: institution2, accountIdentifier: accountIdentifier2, accountName: accountName2 } },
        destination: { type: "crypto", currency: TOKEN, recipient: { address: recipient, network: NETWORK } }
      })
    });
    if (status2 !== 201 && status2 !== 200) {
      console.error("[offramp] deposit failed", status2, body2.message);
      if (status2 === 401 || status2 === 403) {
        return json(503, {
          error: `Paycrest won't take orders from this account yet (${problemText(body2)}). That's their verification, not your wallet \u2014 nothing was sent.`
        });
      }
      return json(400, { error: problemText(body2) });
    }
    const order = body2.data;
    if (!order?.id || !order.providerAccount) {
      console.error("[offramp] unexpected deposit order", JSON.stringify(body2).slice(0, 300));
      return json(502, { error: "Paycrest returned an order we could not read. Nothing was paid." });
    }
    return json(201, { order });
  }
  if (route === "order") {
    if (problem) return json(503, { error: problem });
    const id = url.searchParams.get("id") ?? "";
    if (!/^[A-Za-z0-9-]{10,64}$/.test(id)) return json(400, { error: "bad order id" });
    const { status: status2, body: body2 } = await paycrest(`/sender/orders/${id}`, { authenticated: true });
    if (status2 !== 200) return json(502, { error: problemText(body2) });
    return json(200, { order: body2.data });
  }
  if (route !== "orders" || request.method !== "POST") return json(405, { error: "method not allowed" });
  if (problem) {
    console.error(`[offramp] not configured: ${problem}`);
    return json(503, { error: "Cashing out is not configured on this server." });
  }
  const payload = await request.json().catch(() => null);
  const checked = orderProblem(payload);
  if ("problem" in checked) return json(400, { error: checked.problem });
  const { amount, currency, institution, accountIdentifier, accountName, memo, refundAddress, providerIds } = checked.order;
  const feePercent = env("PAYCREST_FEE_PERCENT");
  const feeAddress = env("PAYCREST_FEE_ADDRESS");
  const { status, body } = await paycrest("/sender/orders", {
    method: "POST",
    authenticated: true,
    body: JSON.stringify({
      amount,
      source: { type: "crypto", currency: TOKEN, network: NETWORK, refundAddress },
      destination: {
        type: "fiat",
        currency,
        ...providerIds.length ? { providerIds } : {},
        recipient: { institution, accountIdentifier, accountName, ...memo ? { memo } : {} }
      },
      ...Number(feePercent) > 0 && isAddress(feeAddress) ? { senderFeePercent: feePercent, senderFeeAddress: feeAddress } : {}
    })
  });
  if (status !== 201 && status !== 200) {
    console.error("[offramp] create failed", status, body.message);
    if (status === 401 || status === 403) {
      return json(503, {
        error: `Paycrest won't take orders from this account yet (${problemText(body)}). That's their verification, not your wallet \u2014 nothing was sent.`
      });
    }
    return json(400, { error: problemText(body) });
  }
  const wrong = depositProblem(body.data);
  if (wrong) {
    console.error(`[offramp] unexpected order: ${wrong}`, JSON.stringify(body).slice(0, 400));
    return json(502, { error: "Paycrest returned an order we could not verify. Nothing was sent." });
  }
  return json(201, { order: body.data });
}
export {
  cleanAmount,
  depositProblem,
  handleOfframp,
  orderProblem
};
