// GENERATED by scripts/build-agent-api.mjs from server/*.ts — do not edit.

// server/onramp.ts
import { createAppServerKit, createSessionRouteHandler } from "@circle-fin/app-kit/server";

// server/chain.ts
import { createPublicClient, createWalletClient, defineChain, fallback, http } from "viem";
import { privateKeyToAccount } from "viem/accounts";
var IS_MAINNET = (process.env.VITE_ARC_NETWORK ?? "").trim() === "mainnet";
var USDC = { symbol: "USDC", address: "0x3600000000000000000000000000000000000000", decimals: 6 };
var NETWORKS = {
  testnet: {
    chainId: 5042002,
    name: "Arc Testnet",
    explorer: "https://explorer.testnet.arc.io",
    rpcs: ["https://rpc.testnet.arc.io", "https://rpc.testnet.arc.network"],
    // Same registry as src/tokens.ts
    tokens: [USDC, { symbol: "EURC", address: "0x89B50855Aa3bE2F677cD6303Cec089B5F319D72a", decimals: 6 }],
    // Synthra — verified: router factory() matches, USDC/EURC pools funded
    swap: {
      venue: "Synthra",
      router: "0xA545bCB1Bd7985c59ea162aB1748A0803434C31b",
      quoter: "0x3Ce954107b1A675826B33bF23060Dd655e3758fE",
      feeTiers: [100, 500, 3e3, 1e4],
      slippageBps: 50n
    },
    arcNames: "0x578dbd5734f13bca66a1355cca296c07823892a2",
    betaMaxPerDay: null
  },
  mainnet: {
    chainId: 5042,
    name: "Arc",
    explorer: "https://explorer.arc.io",
    rpcs: [
      "https://rpc.mainnet.arc.io",
      "https://rpc.blockdaemon.mainnet.arc.io",
      "https://rpc.drpc.mainnet.arc.io",
      "https://rpc.quicknode.mainnet.arc.io"
    ],
    tokens: [USDC],
    // No verified USDC/EURC pools on mainnet yet — the swap tool is off
    swap: null,
    arcNames: "0xF2DCe7fe2864FDD899b12185c610C11d425200d9",
    // Unaudited vault holding real money: refuse vaults whose daily limit is above this
    // (whole tokens; same cap as BETA_MAX_PER_DAY in src/agent-config.ts)
    betaMaxPerDay: 50
  }
};
var NET = IS_MAINNET ? NETWORKS.mainnet : NETWORKS.testnet;
var CHAIN_ID = NET.chainId;
var NETWORK_NAME = NET.name;
var EXPLORER = NET.explorer;
var TOKENS = NET.tokens;
var SWAP = NET.swap;
var ARC_NAMES = NET.arcNames;
var BETA_MAX_PER_DAY = NET.betaMaxPerDay;
var arcChain = defineChain({
  id: CHAIN_ID,
  name: NETWORK_NAME,
  nativeCurrency: { name: "USDC", symbol: "USDC", decimals: 18 },
  rpcUrls: { default: { http: [...NET.rpcs] } }
});
var publicClient = createPublicClient({
  chain: arcChain,
  transport: fallback(arcChain.rpcUrls.default.http.map((u) => http(u, { retryCount: 2, timeout: 15e3 })))
});

// server/onramp.ts
function env(name) {
  return (process.env[name] ?? "").trim().replace(/^["']|["']$/g, "").trim();
}
function configProblem() {
  const key = env("CIRCLE_API_KEY");
  if (!key) return "CIRCLE_API_KEY is not set";
  const testnet = CHAIN_ID !== 5042;
  if (testnet && key.startsWith("LIVE_API_KEY:")) return "CIRCLE_API_KEY is a mainnet (LIVE) key but the app is on Arc Testnet";
  if (!testnet && key.startsWith("TEST_API_KEY:")) return "CIRCLE_API_KEY is a testnet (TEST) key but the app is on Arc mainnet";
  return null;
}
var json = (status, body) => Response.json(body, { status });
var recent = [];
var RATE_WINDOW_MS = 6e4;
var RATE_MAX = 20;
var handler = null;
function sessionHandler(origin) {
  if (!handler) {
    const server = createAppServerKit({
      onramp: {
        apiKey: env("CIRCLE_API_KEY"),
        // Card / Apple Pay / Google Pay require the embedding domain
        referrerDomain: env("ONRAMP_REFERRER_DOMAIN") || new URL(origin).host
      }
    });
    handler = createSessionRouteHandler(server.onramp);
  }
  return handler;
}
async function handleOnramp(route, request) {
  const problem = configProblem();
  if (route === "info" && request.method === "GET") {
    return json(200, { enabled: problem == null, chainId: CHAIN_ID, ...problem ? { reason: problem } : {} });
  }
  if (route !== "sessions" || request.method !== "POST") return json(405, { error: "method not allowed" });
  if (problem) {
    console.error(`[onramp] misconfigured: ${problem}`);
    return json(503, { error: "Card top-ups are not configured on this server." });
  }
  const now = Date.now();
  while (recent.length && now - recent[0] > RATE_WINDOW_MS) recent.shift();
  if (recent.length >= RATE_MAX) return json(429, { error: "Too many top-up sessions right now \u2014 try again in a minute." });
  recent.push(now);
  try {
    return await sessionHandler(new URL(request.url).origin)(request);
  } catch (err) {
    console.error("[onramp] session failed", err);
    return json(502, { error: "Circle could not start a top-up session." });
  }
}
export {
  handleOnramp
};
